name: tedx
description: "TEDx Millennium Language School Website"
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  font_awesome_flutter: ^10.8.0
  flutter_screenutil: ^5.9.3
  url_launcher: ^6.3.1
  get: ^4.7.2
  firebase_core: ^3.13.1
  cloud_firestore: ^5.6.8
  skeletonizer: ^2.0.1
  cloudinary: ^1.2.0
  firebase_auth: ^5.5.4
  flutter_launcher_icons: ^0.14.4


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
